exclude: 'migrations'
repos:
  
 
  - repo: https://github.com/psf/black.git
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
  
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
          - flake8-bugbear
          - flake8-builtins
          - flake8-coding
          - flake8-import-order
          - flake8-polyfill
        language_version: python3

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.910'
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [ types-requests, types-PyYAML, types-toml ]
  # - repo: local
  #   hooks:
  #     - id: django-test
  #       name: django-test
  #       entry: python manage.py test
  #       always_run: true
  #       pass_filenames: false
  #       language: system
  

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  # - repo: https://github.com/pre-commit/mirrors-yapf
  #   rev: v0.31.0
  #   hooks:
  #     - id: yapf
  #       additional_dependencies: [ toml ]
 
